### ISSUE TITLE
Magnet class doesn't behave like a magnet

### ISSUE THREAD

**Issue by stephanbogner** [b-g/p5-matter-examples#11]
We (@b-g and me) used the magnet class in the ["attractor duo" example](https://b-g.github.io/p5-matter-examples/5-attractor-duo/) and noticed that it might not behave like an actual magnet 😆 

I think in reality once an element comes closer to one magnet, it would snap towards that magnet, because pull force is not linear to distance.

Apparently the pull force of a magnet [follows the "inverse square law"](https://socratic.org/questions/how-does-distance-affect-magnetic-force).

Maybe you know more @ByronStar

**Comment by ByronStar** [comment]
I have added Newton's Law of Gravity to the Magnet class as defined in https://github.com/liabru/matter-attractors/blob/master/build/matter-attractors.js libaru's MatterAttractor plugin. The attractor duo example is changed accordingly. The static bodies need mass defined - otherwise ist is Infinite. Please have a look @stephanbogner and comment if this is not the desired result.

**Comment by stephanbogner** [comment]
@ByronStar 
Thanks for fixing this 👍 
I renamed the example back to `magnet` and `magnet-duo` and reexported the docs

> The static bodies need mass defined - otherwise ist is Infinite.
That is good to know too!
